include dracula.conf

window_padding_width 4

font_size 11.0

font_family        JetBrainsMono Nerd Font
bold_font          JetBrainsMono Nerd Font Bold
italic_font        JetBrainsMono Nerd Font Italic
bold_italic_font   JetBrainsMono Nerd Font Bold Italic
